# SPDX-FileCopyrightText: 2026 Enio Kaljic
# SPDX-License-Identifier: AGPL-3.0-or-later

TOPLEVEL_LANG = verilog
SIM = verilator

#
# Top-level module
#
TOPLEVEL = csr

#
# RTL sources
#
VERILOG_SOURCES += $(PWD)/build/rtl/$(TOPLEVEL)_pkg.sv
VERILOG_SOURCES += $(PWD)/build/rtl/$(TOPLEVEL).sv

#
# cocotb test module (without .py)
#
MODULE = verif.Testbench

#
# Verilator flags
#
EXTRA_ARGS += --sv
EXTRA_ARGS += --trace
EXTRA_ARGS += --trace-structs
EXTRA_ARGS += -Wno-fatal

#
# Optional waveform dump
#
PLUSARGS += +trace

#
# Python path
#
export PYTHONPATH := $(PWD):$(PYTHONPATH)

#
# cocotb
#
include $(shell cocotb-config --makefiles)/Makefile.sim

